version: '3.3'

services:
  db:
    build: .
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5436:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres_data:

